export const VIGAN_BARANGAYS = [
  'Barangay I',
  'Barangay II',
  'Barangay III',
  'Barangay IV',
  'Barangay V',
  'Barangay VI',
  'Barangay VII',
  'Barangay VIII',
  'Barangay IX (Cuta)',
  'Ayusan Norte',
  'Ayusan Sur',
  'Barraca',
  'Beddeng Daya',
  'Beddeng Laud',
  'Bongtolan',
  'Bulala',
  'Cabalangegan',
  'Cabaroan Daya',
  'Cabaroan Laud',
  'Camangaan',
  'Capangpangan',
  'Mindoro',
  'Nagsangalan',
  'Pantay Daya',
  'Pantay Fatima',
  'Pantay Laud',
  'Paoa',
  'Paratong',
  'Pong-ol',
  'Purok-a-bassit',
  'Purok-a-dackel',
  'Raois',
  'Rugsuanan',
  'Salindeg',
  'San Jose',
  'San Julian Norte',
  'San Julian Sur',
  'San Pedro',
  'Tamag',
]
