export const VIGAN_BARANGAYS = [
  'Barangay I',
  'Barangay II',
  'Barangay III',
  'Barangay IV',
  'Barangay V',
  'Barangay VI',
  'Barangay VII',
  'Barangay VIII',
  'Barangay IX (Cuta)',
  'Barangay Ayusan Norte',
  'Barangay Ayusan Sur',
  'Barangay Barraca',
  'Barangay Beddeng Daya',
  'Barangay Beddeng Laud',
  'Barangay Bongtolan',
  'Barangay Bulala',
  'Barangay Cabalangegan',
  'Barangay Cabaroan Daya',
  'Barangay Cabaroan Laud',
  'Barangay Camangaan',
  'Barangay Capangpangan',
  'Barangay Mindoro',
  'Barangay Nagsangalan',
  'Barangay Pantay Daya',
  'Barangay Pantay Fatima',
  'Barangay Pantay Laud',
  'Barangay Paoa',
  'Barangay Paratong',
  'Barangay Pong-ol',
  'Barangay Purok-a-bassit',
  'Barangay Purok-a-dackel',
  'Barangay Raois',
  'Barangay Rugsuanan',
  'Barangay Salindeg',
  'Barangay San Jose',
  'Barangay San Julian Norte',
  'Barangay San Julian Sur',
  'Barangay San Pedro',
  'Barangay Tamag',
]
